"""Protocol classes for spec ports.

Protocols document the operations every adapter (in-memory, sqlite, http) must
implement. The in-memory adapters live in `adapters.py`; production packs swap them
for real persistence.
"""

from typing import Protocol

from entitlements_app.entities import AccountOverride, AuditEvent, Entitlement, Feature, Plan, PolicyCheckResult, Subscription, UsageMeter



class EntitlementsRepository(Protocol):
    """Persistence port for plans, features, subscriptions, usage meters, overrides, policy decisions, and audit events."""
    def savePlan(self, plan: Plan) -> Plan: ...
    def save_plan(self, plan: Plan) -> Plan: ...
    def findPlan(self, planId: str) -> Plan: ...
    def find_plan(self, plan_id: str) -> Plan: ...
    def saveFeature(self, feature: Feature) -> Feature: ...
    def save_feature(self, feature: Feature) -> Feature: ...
    def findFeature(self, featureKey: str) -> Feature: ...
    def find_feature(self, feature_key: str) -> Feature: ...
    def saveEntitlement(self, entitlement: Entitlement) -> Entitlement: ...
    def save_entitlement(self, entitlement: Entitlement) -> Entitlement: ...
    def findEntitlement(self, entitlementId: str) -> Entitlement: ...
    def find_entitlement(self, entitlement_id: str) -> Entitlement: ...
    def listEntitlementsByPlan(self, planId: str) -> list[Entitlement]: ...
    def list_entitlements_by_plan(self, plan_id: str) -> list[Entitlement]: ...
    def saveSubscription(self, subscription: Subscription) -> Subscription: ...
    def save_subscription(self, subscription: Subscription) -> Subscription: ...
    def findSubscription(self, subscriptionId: str) -> Subscription: ...
    def find_subscription(self, subscription_id: str) -> Subscription: ...
    def listSubscriptionsByAccount(self, accountId: str) -> list[Subscription]: ...
    def list_subscriptions_by_account(self, account_id: str) -> list[Subscription]: ...
    def saveUsageMeter(self, usageMeter: UsageMeter) -> UsageMeter: ...
    def save_usage_meter(self, usage_meter: UsageMeter) -> UsageMeter: ...
    def findUsageMeter(self, usageId: str) -> UsageMeter: ...
    def find_usage_meter(self, usage_id: str) -> UsageMeter: ...
    def listUsageBySubscription(self, subscriptionId: str) -> list[UsageMeter]: ...
    def list_usage_by_subscription(self, subscription_id: str) -> list[UsageMeter]: ...
    def saveAccountOverride(self, accountOverride: AccountOverride) -> AccountOverride: ...
    def save_account_override(self, account_override: AccountOverride) -> AccountOverride: ...
    def findAccountOverride(self, overrideId: str) -> AccountOverride: ...
    def find_account_override(self, override_id: str) -> AccountOverride: ...
    def listOverridesByAccount(self, accountId: str) -> list[AccountOverride]: ...
    def list_overrides_by_account(self, account_id: str) -> list[AccountOverride]: ...
    def savePolicyCheckResult(self, policyCheckResult: PolicyCheckResult) -> PolicyCheckResult: ...
    def save_policy_check_result(self, policy_check_result: PolicyCheckResult) -> PolicyCheckResult: ...
    def findPolicyCheckResult(self, decisionId: str) -> PolicyCheckResult: ...
    def find_policy_check_result(self, decision_id: str) -> PolicyCheckResult: ...
    def saveAuditEvent(self, auditEvent: AuditEvent) -> AuditEvent: ...
    def save_audit_event(self, audit_event: AuditEvent) -> AuditEvent: ...
    def listAuditEventsByAccount(self, accountId: str) -> list[AuditEvent]: ...
    def list_audit_events_by_account(self, account_id: str) -> list[AuditEvent]: ...
